### ISSUE TITLE
docker compose yaml file example

### ISSUE THREAD

**Issue by tomhub** [matiasdelellis/facerecognition-external-model#9]
docker-compose.yaml example, not sure if environment is required here. Is the setup of FACE_MODEL correct ?
```
version: '3'
services:
  facerecognition:
    container_name: facerecognition
    restart: unless-stopped
#    image: ghcr.io/matiasdelellis/facerecognition-external-model:latest
    build: https://github.com/matiasdelellis/facerecognition-external-model.git

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/facerecognition/api.key:/app/api.key:ro
      - type: tmpfs # Optional: 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1GB
    ports:
      - "8080:5000"
    environment:
      FACE_MODEL: 4
```
